---
- name: Configure Ubuntu and install common packages
  hosts: all
  become: true
  roles:
    - common

- name: Install and configure Consul
  hosts: all
  become: true
  roles:
    - consul

- name: Install and configure Nomad servers
  hosts: servers
  become: true
  vars:
    nomad_server_enabled: true
    nomad_server_bootstrap_expect: "{{ groups['servers'] | length }}"
  roles:
    - nomad

- name: Install and configure Nomad clients
  hosts: clients
  become: true
  vars:
    nomad_client_enabled: true
  roles:
    - nomad

# Made with Bob
